// src/database/migrations/1660000000002-SeedDistricts.ts
import { MigrationInterface, QueryRunner } from 'typeorm';
export class SeedDistricts1660000000002 implements MigrationInterface {
  private readonly districts: Array<{ name: string; code: string; departmentCode: string }> = [
 // -------- Ahuachapán (01) --------
  { name: 'Ahuachapán', code: '001', departmentCode: '01' },
  { name: 'Apaneca', code: '002', departmentCode: '01' },
  { name: 'Atiquizaya', code: '003', departmentCode: '01' },
  { name: 'Concepción de Ataco', code: '004', departmentCode: '01' },
  { name: 'El Refugio', code: '005', departmentCode: '01' },
  { name: 'Guaymango', code: '006', departmentCode: '01' },
  { name: 'Jujutla', code: '007', departmentCode: '01' },
  { name: 'San Francisco Menéndez', code: '008', departmentCode: '01' },
  { name: 'San Lorenzo', code: '009', departmentCode: '01' },
  { name: 'San Pedro Puxtla', code: '010', departmentCode: '01' },
  { name: 'Tacuba', code: '011', departmentCode: '01' },
  { name: 'Turín', code: '012', departmentCode: '01' },

  // -------- Cabañas (02) --------
  { name: 'Cinquera', code: '013', departmentCode: '02' },
  { name: 'Dolores', code: '014', departmentCode: '02' },
  { name: 'Guacotecti', code: '015', departmentCode: '02' },
  { name: 'Ilobasco', code: '016', departmentCode: '02' },
  { name: 'Jutiapa', code: '017', departmentCode: '02' },
  { name: 'San Isidro', code: '018', departmentCode: '02' },
  { name: 'Sensuntepeque', code: '019', departmentCode: '02' },
  { name: 'Tejutepeque', code: '020', departmentCode: '02' },
  { name: 'Victoria', code: '021', departmentCode: '02' },

  // -------- Chalatenango (03) --------
  { name: 'Agua Caliente', code: '022', departmentCode: '03' },
  { name: 'Arcatao', code: '023', departmentCode: '03' },
  { name: 'Azacualpa', code: '024', departmentCode: '03' },
  { name: 'Chalatenango', code: '025', departmentCode: '03' },
  { name: 'Citalá', code: '026', departmentCode: '03' },
  { name: 'Comalapa', code: '027', departmentCode: '03' },
  { name: 'Concepción Quezaltepeque', code: '028', departmentCode: '03' },
  { name: 'Dulce Nombre de María', code: '029', departmentCode: '03' },
  { name: 'El Carrizal', code: '030', departmentCode: '03' },
  { name: 'El Paraíso', code: '031', departmentCode: '03' },
  { name: 'La Laguna', code: '032', departmentCode: '03' },
  { name: 'La Palma', code: '033', departmentCode: '03' },
  { name: 'La Reina', code: '034', departmentCode: '03' },
  { name: 'Las Flores (San José Las Flores)', code: '035', departmentCode: '03' },
  { name: 'Las Vueltas', code: '036', departmentCode: '03' },
  { name: 'Nombre de Jesús', code: '037', departmentCode: '03' },
  { name: 'Nueva Concepción', code: '038', departmentCode: '03' },
  { name: 'Nueva Trinidad', code: '039', departmentCode: '03' },
  { name: 'Ojos de Agua', code: '040', departmentCode: '03' },
  { name: 'Potonico', code: '041', departmentCode: '03' },
  { name: 'San Antonio de la Cruz', code: '042', departmentCode: '03' },
  { name: 'San Antonio Los Ranchos', code: '043', departmentCode: '03' },
  { name: 'San Fernando', code: '044', departmentCode: '03' },
  { name: 'San Francisco Lempa', code: '045', departmentCode: '03' },
  { name: 'San Francisco Morazán', code: '046', departmentCode: '03' },
  { name: 'San Ignacio', code: '047', departmentCode: '03' },
  { name: 'San Isidro Labrador', code: '048', departmentCode: '03' },
  { name: 'San José Cancasque', code: '049', departmentCode: '03' },
  { name: 'San Luis del Carmen', code: '050', departmentCode: '03' },
  { name: 'San Miguel de Mercedes', code: '051', departmentCode: '03' },
  { name: 'San Rafael', code: '052', departmentCode: '03' },
  { name: 'Santa Rita', code: '053', departmentCode: '03' },
  { name: 'Tejutla', code: '054', departmentCode: '03' },

  // -------- Cuscatlán (04) --------
  { name: 'Candelaria', code: '055', departmentCode: '04' },
  { name: 'Cojutepeque', code: '056', departmentCode: '04' },
  { name: 'El Carmen', code: '057', departmentCode: '04' },
  { name: 'El Rosario', code: '058', departmentCode: '04' },
  { name: 'Monte San Juan', code: '059', departmentCode: '04' },
  { name: 'Oratorio de Concepción', code: '060', departmentCode: '04' },
  { name: 'San Bartolomé Perulapía', code: '061', departmentCode: '04' },
  { name: 'San Cristóbal', code: '062', departmentCode: '04' },
  { name: 'San José Guayabal', code: '063', departmentCode: '04' },
  { name: 'San Pedro Perulapán', code: '064', departmentCode: '04' },
  { name: 'San Rafael Cedros', code: '065', departmentCode: '04' },
  { name: 'San Ramón', code: '066', departmentCode: '04' },
  { name: 'Santa Cruz Analquito', code: '067', departmentCode: '04' },
  { name: 'Santa Cruz Michapa', code: '068', departmentCode: '04' },
  { name: 'Suchitoto', code: '069', departmentCode: '04' },
  { name: 'Tenancingo', code: '070', departmentCode: '04' },

  // -------- La Libertad (05) --------
  { name: 'Antiguo Cuscatlán', code: '071', departmentCode: '05' },
  { name: 'Chiltiupán', code: '072', departmentCode: '05' },
  { name: 'Ciudad Arce', code: '073', departmentCode: '05' },
  { name: 'Colón', code: '074', departmentCode: '05' },
  { name: 'Comasagua', code: '075', departmentCode: '05' },
  { name: 'Huizúcar', code: '076', departmentCode: '05' },
  { name: 'Jayaque', code: '077', departmentCode: '05' },
  { name: 'Jicalapa', code: '078', departmentCode: '05' },
  { name: 'La Libertad', code: '079', departmentCode: '05' },
  { name: 'Nuevo Cuscatlán', code: '080', departmentCode: '05' },
  { name: 'Quezaltepeque', code: '081', departmentCode: '05' },
  { name: 'Sacacoyo', code: '082', departmentCode: '05' },
  { name: 'San José Villanueva', code: '083', departmentCode: '05' },
  { name: 'San Juan Opico', code: '084', departmentCode: '05' },
  { name: 'San Matías', code: '085', departmentCode: '05' },
  { name: 'San Pablo Tacachico', code: '086', departmentCode: '05' },
  { name: 'Santa Tecla', code: '087', departmentCode: '05' },
  { name: 'Talnique', code: '088', departmentCode: '05' },
  { name: 'Tamanique', code: '089', departmentCode: '05' },
  { name: 'Teotepeque', code: '090', departmentCode: '05' },
  { name: 'Tepecoyo', code: '091', departmentCode: '05' },
  { name: 'Zaragoza', code: '092', departmentCode: '05' },

  // -------- La Paz (06) --------
  { name: 'Cuyultitán', code: '093', departmentCode: '06' },
  { name: 'El Rosario', code: '094', departmentCode: '06' },
  { name: 'Jerusalén', code: '095', departmentCode: '06' },
  { name: 'Mercedes La Ceiba', code: '096', departmentCode: '06' },
  { name: 'Olocuilta', code: '097', departmentCode: '06' },
  { name: 'Paraíso de Osorio', code: '098', departmentCode: '06' },
  { name: 'San Antonio Masahuat', code: '099', departmentCode: '06' },
  { name: 'San Emigdio', code: '100', departmentCode: '06' },
  { name: 'San Francisco Chinameca', code: '101', departmentCode: '06' },
  { name: 'San Juan Nonualco', code: '102', departmentCode: '06' },
  { name: 'San Juan Talpa', code: '103', departmentCode: '06' },
  { name: 'San Juan Tepezontes', code: '104', departmentCode: '06' },
  { name: 'San Luis La Herradura', code: '105', departmentCode: '06' },
  { name: 'San Luis Talpa', code: '106', departmentCode: '06' },
  { name: 'San Miguel Tepezontes', code: '107', departmentCode: '06' },
  { name: 'San Pedro Masahuat', code: '108', departmentCode: '06' },
  { name: 'San Pedro Nonualco', code: '109', departmentCode: '06' },
  { name: 'San Rafael Obrajuelo', code: '110', departmentCode: '06' },
  { name: 'Santa María Ostuma', code: '111', departmentCode: '06' },
  { name: 'Santiago Nonualco', code: '112', departmentCode: '06' },
  { name: 'Tapalhuaca', code: '113', departmentCode: '06' },
  { name: 'Zacatecoluca', code: '114', departmentCode: '06' },

  // -------- La Unión (07) --------
  { name: 'Anamorós', code: '115', departmentCode: '07' },
  { name: 'Bolívar', code: '116', departmentCode: '07' },
  { name: 'Concepción de Oriente', code: '117', departmentCode: '07' },
  { name: 'Conchagua', code: '118', departmentCode: '07' },
  { name: 'El Carmen', code: '119', departmentCode: '07' },
  { name: 'El Sauce', code: '120', departmentCode: '07' },
  { name: 'Intipucá', code: '121', departmentCode: '07' },
  { name: 'La Unión', code: '122', departmentCode: '07' },
  { name: 'Lislique', code: '123', departmentCode: '07' },
  { name: 'Meanguera del Golfo', code: '124', departmentCode: '07' },
  { name: 'Nueva Esparta', code: '125', departmentCode: '07' },
  { name: 'Pasaquina', code: '126', departmentCode: '07' },
  { name: 'Polorós', code: '127', departmentCode: '07' },
  { name: 'San Alejo', code: '128', departmentCode: '07' },
  { name: 'San José', code: '129', departmentCode: '07' },
  { name: 'Santa Rosa de Lima', code: '130', departmentCode: '07' },
  { name: 'Yayantique', code: '131', departmentCode: '07' },
  { name: 'Yucuaiquín', code: '132', departmentCode: '07' },

  // -------- Morazán (08) --------
  { name: 'Arambala', code: '133', departmentCode: '08' },
  { name: 'Cacaopera', code: '134', departmentCode: '08' },
  { name: 'Chilanga', code: '135', departmentCode: '08' },
  { name: 'Corinto', code: '136', departmentCode: '08' },
  { name: 'Delicias de Concepción', code: '137', departmentCode: '08' },
  { name: 'El Divisadero', code: '138', departmentCode: '08' },
  { name: 'El Rosario', code: '139', departmentCode: '08' },
  { name: 'Gualococti', code: '140', departmentCode: '08' },
  { name: 'Guatajiagua', code: '141', departmentCode: '08' },
  { name: 'Joateca', code: '142', departmentCode: '08' },
  { name: 'Jocoaitique', code: '143', departmentCode: '08' },
  { name: 'Jocoro', code: '144', departmentCode: '08' },
  { name: 'Lolotiquillo', code: '145', departmentCode: '08' },
  { name: 'Meanguera', code: '146', departmentCode: '08' },
  { name: 'Osicala', code: '147', departmentCode: '08' },
  { name: 'Perquín', code: '148', departmentCode: '08' },
  { name: 'San Carlos', code: '149', departmentCode: '08' },
  { name: 'San Fernando', code: '150', departmentCode: '08' },
  { name: 'San Francisco Gotera', code: '151', departmentCode: '08' },
  { name: 'San Isidro', code: '152', departmentCode: '08' },
  { name: 'San Simón', code: '153', departmentCode: '08' },
  { name: 'Sensembra', code: '154', departmentCode: '08' },
  { name: 'Sociedad', code: '155', departmentCode: '08' },
  { name: 'Torola', code: '156', departmentCode: '08' },
  { name: ' средствами (Tualteca/Yamabal)', code: '157', departmentCode: '08' }, // Yamabal
  { name: 'Yoloaiquín', code: '158', departmentCode: '08' },

  // -------- San Miguel (09) --------
  { name: 'Carolina', code: '159', departmentCode: '09' },
  { name: 'Chapeltique', code: '160', departmentCode: '09' },
  { name: 'Chinameca', code: '161', departmentCode: '09' },
  { name: 'Chirilagua', code: '162', departmentCode: '09' },
  { name: 'Ciudad Barrios', code: '163', departmentCode: '09' },
  { name: 'Comacarán', code: '164', departmentCode: '09' },
  { name: 'El Tránsito', code: '165', departmentCode: '09' },
  { name: 'Lolotique', code: '166', departmentCode: '09' },
  { name: 'Moncagua', code: '167', departmentCode: '09' },
  { name: 'Nueva Guadalupe', code: '168', departmentCode: '09' },
  { name: 'Nuevo Edén de San Juan', code: '169', departmentCode: '09' },
  { name: 'Quelepa', code: '170', departmentCode: '09' },
  { name: 'San Antonio', code: '171', departmentCode: '09' },
  { name: 'San Gerardo', code: '172', departmentCode: '09' },
  { name: 'San Jorge', code: '173', departmentCode: '09' },
  { name: 'San Luis de la Reina', code: '174', departmentCode: '09' },
  { name: 'San Miguel', code: '175', departmentCode: '09' },
  { name: 'San Rafael Oriente', code: '176', departmentCode: '09' },
  { name: 'Sesori', code: '177', departmentCode: '09' },
  { name: 'Uluazapa', code: '178', departmentCode: '09' },

  // -------- San Salvador (10) --------
  { name: 'Aguilares', code: '179', departmentCode: '10' },
  { name: 'Apopa', code: '180', departmentCode: '10' },
  { name: 'Ayutuxtepeque', code: '181', departmentCode: '10' },
  { name: 'Cuscatancingo', code: '182', departmentCode: '10' },
  { name: 'Delgado', code: '183', departmentCode: '10' },
  { name: 'El Paisnal', code: '184', departmentCode: '10' },
  { name: 'Guazapa', code: '185', departmentCode: '10' },
  { name: 'Ilopango', code: '186', departmentCode: '10' },
  { name: 'Mejicanos', code: '187', departmentCode: '10' },
  { name: 'Nejapa', code: '188', departmentCode: '10' },
  { name: 'Panchimalco', code: '189', departmentCode: '10' },
  { name: 'Rosario de Mora', code: '190', departmentCode: '10' },
  { name: 'San Marcos', code: '191', departmentCode: '10' },
  { name: 'San Martín', code: '192', departmentCode: '10' },
  { name: 'San Salvador', code: '193', departmentCode: '10' },
  { name: 'Santiago Texacuangos', code: '194', departmentCode: '10' },
  { name: 'Santo Tomás', code: '195', departmentCode: '10' },
  { name: 'Soyapango', code: '196', departmentCode: '10' },
  { name: 'Tonacatepeque', code: '197', departmentCode: '10' },

  // -------- San Vicente (11) --------
  { name: 'Apastepeque', code: '198', departmentCode: '11' },
  { name: 'Guadalupe', code: '199', departmentCode: '11' },
  { name: 'San Cayetano Istepeque', code: '200', departmentCode: '11' },
  { name: 'San Esteban Catarina', code: '201', departmentCode: '11' },
  { name: 'San Ildefonso', code: '202', departmentCode: '11' },
  { name: 'San Lorenzo', code: '203', departmentCode: '11' },
  { name: 'San Sebastián', code: '204', departmentCode: '11' },
  { name: 'San Vicente', code: '205', departmentCode: '11' },
  { name: 'Santa Clara', code: '206', departmentCode: '11' },
  { name: 'Santo Domingo', code: '207', departmentCode: '11' },
  { name: 'Tecoluca', code: '208', departmentCode: '11' },
  { name: 'Tepetitán', code: '209', departmentCode: '11' },
  { name: 'Verapaz', code: '210', departmentCode: '11' },

  // -------- Santa Ana (12) --------
  { name: 'Candelaria de la Frontera', code: '211', departmentCode: '12' },
  { name: 'Chalchuapa', code: '212', departmentCode: '12' },
  { name: 'Coatepeque', code: '213', departmentCode: '12' },
  { name: 'El Congo', code: '214', departmentCode: '12' },
  { name: 'El Porvenir', code: '215', departmentCode: '12' },
  { name: 'Masahuat', code: '216', departmentCode: '12' },
  { name: 'Metapán', code: '217', departmentCode: '12' },
  { name: 'San Antonio Pajonal', code: '218', departmentCode: '12' },
  { name: 'San Sebastián Salitrillo', code: '219', departmentCode: '12' },
  { name: 'Santa Ana', code: '220', departmentCode: '12' },
  { name: 'Santa Rosa Guachipilín', code: '221', departmentCode: '12' },
  { name: 'Santiago de la Frontera', code: '222', departmentCode: '12' },
  { name: 'Texistepeque', code: '223', departmentCode: '12' },

  // -------- Sonsonate (13) --------
  { name: 'Acajutla', code: '224', departmentCode: '13' },
  { name: 'Armenia', code: '225', departmentCode: '13' },
  { name: 'Caluco', code: '226', departmentCode: '13' },
  { name: 'Cuisnahuat', code: '227', departmentCode: '13' },
  { name: 'Izalco', code: '228', departmentCode: '13' },
  { name: 'Juayúa', code: '229', departmentCode: '13' },
  { name: 'Nahuizalco', code: '230', departmentCode: '13' },
  { name: 'Nahulingo', code: '231', departmentCode: '13' },
  { name: 'Salcoatitán', code: '232', departmentCode: '13' },
  { name: 'San Antonio del Monte', code: '233', departmentCode: '13' },
  { name: 'San Julián', code: '234', departmentCode: '13' },
  { name: 'Santa Catarina Masahuat', code: '235', departmentCode: '13' },
  { name: 'Santa Isabel Ishuatán', code: '236', departmentCode: '13' },
  { name: 'Santo Domingo de Guzmán', code: '237', departmentCode: '13' },
  { name: 'Sonsonate', code: '238', departmentCode: '13' },
  { name: 'Sonzacate', code: '239', departmentCode: '13' },

  // -------- Usulután (14) --------
  { name: 'Alegría', code: '240', departmentCode: '14' },
  { name: 'Berlín', code: '241', departmentCode: '14' },
  { name: 'California', code: '242', departmentCode: '14' },
  { name: 'Concepción Batres', code: '243', departmentCode: '14' },
  { name: 'El Triunfo', code: '244', departmentCode: '14' },
  { name: 'Ereguayquín', code: '245', departmentCode: '14' },
  { name: 'Estanzuelas', code: '246', departmentCode: '14' },
  { name: 'Jiquilisco', code: '247', departmentCode: '14' },
  { name: 'Jucuapa', code: '248', departmentCode: '14' },
  { name: 'Jucuarán', code: '249', departmentCode: '14' },
  { name: 'Mercedes Umaña', code: '250', departmentCode: '14' },
  { name: 'Nueva Granada', code: '251', departmentCode: '14' },
  { name: 'Ozatlán', code: '252', departmentCode: '14' },
  { name: 'Puerto El Triunfo', code: '253', departmentCode: '14' },
  { name: 'San Agustín', code: '254', departmentCode: '14' },
  { name: 'San Buenaventura', code: '255', departmentCode: '14' },
  { name: 'San Dionisio', code: '256', departmentCode: '14' },
  { name: 'San Francisco Javier', code: '257', departmentCode: '14' },
  { name: 'Santa Elena', code: '258', departmentCode: '14' },
  { name: 'Santa María', code: '259', departmentCode: '14' },
  { name: 'Santiago de María', code: '260', departmentCode: '14' },
  { name: 'Tecapán', code: '261', departmentCode: '14' },
  { name: 'Usulután', code: '262', departmentCode: '14' }
  ];

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const d of this.districts) {
      await queryRunner.query(
        `INSERT INTO districts (id, name, code, department_id, is_active, created_at, updated_at)
         VALUES (uuid_generate_v4(), $1, $2, (SELECT id FROM departments WHERE code = $3), true, now(), now()) ON CONFLICT (code) DO NOTHING`,
        [d.name, d.code, d.departmentCode],
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const codes = this.districts.map(d => `'${d.code}'`).join(',');
    await queryRunner.query(`DELETE FROM districts WHERE code IN (${codes});`);
  }
}
