import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1787531417898 implements MigrationInterface {
    name = 'InitialSchema1787531417898'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "supplier_purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'PENDIENTE', "type" character varying(50) NOT NULL DEFAULT 'PENDIENTE', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4c64543c5c0934a781b349117c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "contact_name" character varying(150), "phone" character varying(30), "email" character varying(150), "address" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_5b5720d9645cee7396595a16c93" UNIQUE ("name"), CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "nombre" character varying NOT NULL, "descripcion" text, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supplier_purchase_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchase_id" uuid NOT NULL, "sku" character varying(100) NOT NULL, "size" character varying(50) NOT NULL, "color" character varying(7) NOT NULL, "quantity" integer NOT NULL, "unit_cost" numeric(10,2) NOT NULL, "subtotal" numeric(12,2) NOT NULL, "inventory_detail_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6097ff692c92a7a965afc64bf24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7bb0dbf021a8e44bf92569723b" ON "supplier_purchase_items" ("purchase_id", "sku") `);
        await queryRunner.query(`CREATE TABLE "purchase_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchase_id" uuid NOT NULL, "from_status" character varying(20), "to_status" character varying(20) NOT NULL, "changed_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9bef6b5d011d3da4b58ba0fd849" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sku" character varying(100) NOT NULL, "size" character varying(50) NOT NULL, "color" character varying(7) NOT NULL, "stock" integer NOT NULL DEFAULT '0', "unit_cost" numeric(10,2) NOT NULL DEFAULT '0', "min_stock" integer NOT NULL DEFAULT '0', "inventory_id" uuid NOT NULL, "purchase_item_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_bbe72ff23c8d75eb4bb6c4d191f" UNIQUE ("sku"), CONSTRAINT "REL_f11f9f675827128cf1d7418bc5" UNIQUE ("purchase_item_id"), CONSTRAINT "color_hex_format" CHECK (color ~ '^#[0-9a-fA-F]{6}$'), CONSTRAINT "min_stock_non_negative" CHECK (min_stock >= 0), CONSTRAINT "unit_cost_non_negative" CHECK (unit_cost >= 0), CONSTRAINT "stock_non_negative" CHECK (stock >= 0), CONSTRAINT "PK_683768d20320aec50b45e7b0e7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_634d300a22785103ea37759377" ON "inventory_details" ("inventory_id", "size", "color") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_gender_enum" AS ENUM('FEMALE', 'MALE', 'UNISEX')`);
        await queryRunner.query(`CREATE TYPE "public"."inventories_status_enum" AS ENUM('ACTIVE', 'LOW_STOCK', 'OUT_OF_STOCK')`);
        await queryRunner.query(`CREATE TABLE "inventories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_name" character varying(200) NOT NULL, "brand" character varying(100) NOT NULL, "gender" "public"."inventory_gender_enum", "main_image_url" character varying(500), "status" "public"."inventories_status_enum" NOT NULL DEFAULT 'ACTIVE', "supplier_id" uuid, "category_id" integer, "purchase_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "stock" numeric(12,4) NOT NULL DEFAULT '0', "reserved" numeric(12,4) NOT NULL DEFAULT '0', "product_id" uuid, "created_by" uuid, CONSTRAINT "REL_5f8ef4645f837ca835e90d78c5" UNIQUE ("purchase_id"), CONSTRAINT "REL_92fc0c77bab4a656b9619322c6" UNIQUE ("product_id"), CONSTRAINT "PK_7b1946392ffdcb50cfc6ac78c0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_efd425ab4b2785296c01ac6780" ON "inventories" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bed26289926c1ad4a08d4c728" ON "inventories" ("supplier_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_85e09f62b3421df796c3eb3f68" ON "inventories" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fec544b61606dfdf6e6a3fbac8" ON "inventories" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "product_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "image_url" character varying(500) NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "tag" character varying(50) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e96bca3cd7a592009f2c9dc6f3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_variant_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "inventory_detail_id" uuid NOT NULL, "min_stock" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a04bb3d8fc6d85e963e86f680e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'DISCONTINUED')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "inventory_id" uuid, "commercial_name" character varying(200) NOT NULL, "description" text, "sale_price" numeric(10,2) NOT NULL, "discount" numeric(5,2) DEFAULT '0', "discount_ends_at" TIMESTAMP WITH TIME ZONE, "discount_starts_at" TIMESTAMP WITH TIME ZONE, "status" "public"."products_status_enum" NOT NULL DEFAULT 'DRAFT', "created_by" uuid, "updated_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_834b52ac77bc55fc5d0eb014ae2" UNIQUE ("inventory_id"), CONSTRAINT "REL_834b52ac77bc55fc5d0eb014ae" UNIQUE ("inventory_id"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_89e3b22b462d6443591a1ced4b" ON "products" ("discount_ends_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0166bf08eec9642fecc5da3c9d" ON "products" ("discount_starts_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_995d8194c43edfc98838cabc5a" ON "products" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_166502bbaa3dfc7a5a7ac62c64" ON "products" ("sale_price") `);
        await queryRunner.query(`CREATE INDEX "IDX_1846199852a695713b1f8f5e9a" ON "products" ("status") `);
        await queryRunner.query(`CREATE TABLE "cart_items" ("id" SERIAL NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "unitPrice" numeric(10,2) NOT NULL, "subtotal" numeric(10,2) NOT NULL, "cartId" integer, "productId" uuid, CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "carts" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "REL_69828a178f152f157dcf2f70a8" UNIQUE ("userId"), CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "description" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(80) NOT NULL, "description" character varying(255), "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying(255) NOT NULL, "used" boolean NOT NULL DEFAULT false, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying(255) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "replaced_by_token_hash" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b85ba602ae65eb5813f09e3cec" ON "refresh_tokens" ("user_id", "revoked") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "email" character varying(150) NOT NULL, "password_hash" character varying(255) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "isBlocked" boolean NOT NULL DEFAULT false, "must_change_password" boolean NOT NULL DEFAULT true, "failed_login_attempts" smallint NOT NULL DEFAULT '0', "locked_until" TIMESTAMP WITH TIME ZONE, "token_version" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" integer NOT NULL, "unitPrice" numeric(12,2) NOT NULL, "sale_price_snapshot" numeric(10,2) NOT NULL DEFAULT '0', "discount_snapshot" numeric(5,2) DEFAULT '0', "subtotal" numeric(12,2) NOT NULL DEFAULT '0', "size" character varying(50), "color" character varying(50), "sku" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "orderId" uuid, "productId" uuid, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "address" character varying(255), "phone" character varying(50), "is_active" boolean NOT NULL DEFAULT true, "allows_pickup" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8387ed27b3d4ca53ec3fc7b029c" UNIQUE ("name"), CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8387ed27b3d4ca53ec3fc7b029" ON "branches" ("name") `);
        await queryRunner.query(`CREATE TABLE "order_deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trackingNumber" character varying, "estimatedDeliveryDate" date, "department" character varying(100), "district" character varying(100), "city" character varying(100), "address_line" character varying(255), "branch_id" uuid, "branch_name" character varying(100), "branch_address" character varying(255), "branch_phone" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5b7398f333a716f83e82d8679d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "guest_customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "name" character varying, "phone" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0a9ac17dd8672956c110de98427" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_history_status_before_enum" AS ENUM('NEW', 'PENDING', 'ON_ROUTE', 'READY_FOR_PICKUP', 'DELIVERED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_history_status_after_enum" AS ENUM('NEW', 'PENDING', 'ON_ROUTE', 'READY_FOR_PICKUP', 'DELIVERED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "order_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_before" "public"."order_status_history_status_before_enum", "status_after" "public"."order_status_history_status_after_enum" NOT NULL, "changed_by_id" uuid, "notes" text, "changed_at" TIMESTAMP NOT NULL DEFAULT now(), "order_id" uuid, CONSTRAINT "PK_e6c66d853f155531985fc4f6ec8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('NEW', 'PENDING', 'ON_ROUTE', 'READY_FOR_PICKUP', 'DELIVERED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_delivery_method_enum" AS ENUM('HOME_DELIVERY', 'PICKUP')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderNumber" character varying(8) NOT NULL, "subtotal" numeric(12,2) NOT NULL DEFAULT '0.00', "discount_total" numeric(12,2) NOT NULL DEFAULT '0.00', "delivery_cost" numeric(12,2) NOT NULL DEFAULT '0.00', "total_amount" numeric(12,2) NOT NULL DEFAULT '0.00', "status" "public"."orders_status_enum" NOT NULL DEFAULT 'NEW', "delivery_method" "public"."orders_delivery_method_enum" NOT NULL DEFAULT 'HOME_DELIVERY', "customer_id" uuid, "guest_customer_id" uuid, "customer_email" character varying(150), "customer_name" character varying(150), "customer_phone" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deliveryId" uuid, CONSTRAINT "UQ_59b0c3b34ea0fa5562342f24143" UNIQUE ("orderNumber"), CONSTRAINT "REL_0dddcc76db9733e86e566e5e63" UNIQUE ("deliveryId"), CONSTRAINT "orders_totals_non_negative" CHECK ("subtotal" >= 0 AND "discount_total" >= 0 AND "delivery_cost" >= 0 AND "total_amount" >= 0), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_movements_type_enum" AS ENUM('Entrada', 'Salida')`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_movement_channel_enum" AS ENUM('TIENDA_FISICA', 'ECOMMERCE')`);
        await queryRunner.query(`CREATE TABLE "inventory_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."inventory_movements_type_enum" NOT NULL, "quantity" numeric(12,4) NOT NULL, "stock_before" numeric(12,4) NOT NULL, "stock_after" numeric(12,4) NOT NULL, "notes" character varying(255), "reference_id" uuid, "channel" "public"."inventory_movement_channel_enum" NOT NULL DEFAULT 'TIENDA_FISICA', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "product_id" uuid, "created_by" uuid, "inventory_detail_id" uuid, CONSTRAINT "PK_d7597827c1dcffae889db3ab873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("permission_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("permission_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "reference" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "purchase_date" date`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "brand" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "category_id" integer`);
        await queryRunner.query(`CREATE TYPE "public"."product_gender_enum" AS ENUM('FEMALE', 'MALE', 'UNISEX')`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "gender" "public"."product_gender_enum"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "product_name" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "total_amount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "total_quantity" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "invoice_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "inventory_id" uuid`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "created_by" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "type" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "status" character varying(20) NOT NULL DEFAULT 'COMPLETED'`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e37cfe037f4a370e4494b0eae3" ON "supplier_purchases" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_43f20df28ee6de4d544a9b3972" ON "supplier_purchases" ("category_id") `);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD CONSTRAINT "FK_839283a834244be65640b1e65e3" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_purchase_items" ADD CONSTRAINT "FK_6c99b78100e3d0b47a64aae7ca0" FOREIGN KEY ("purchase_id") REFERENCES "supplier_purchases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_status_history" ADD CONSTRAINT "FK_5b3437860a4a85266ee81df095e" FOREIGN KEY ("purchase_id") REFERENCES "supplier_purchases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD CONSTRAINT "FK_e6b43e8b9b8a6ecf77f34bf86a4" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_details" ADD CONSTRAINT "FK_b6dfdb4875a0860ba9f89bb2e93" FOREIGN KEY ("inventory_id") REFERENCES "inventories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_details" ADD CONSTRAINT "FK_f11f9f675827128cf1d7418bc53" FOREIGN KEY ("purchase_item_id") REFERENCES "supplier_purchase_items"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventories" ADD CONSTRAINT "FK_3bed26289926c1ad4a08d4c7285" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventories" ADD CONSTRAINT "FK_85e09f62b3421df796c3eb3f687" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventories" ADD CONSTRAINT "FK_5f8ef4645f837ca835e90d78c5c" FOREIGN KEY ("purchase_id") REFERENCES "supplier_purchases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventories" ADD CONSTRAINT "FK_92fc0c77bab4a656b9619322c62" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_tags" ADD CONSTRAINT "FK_5b0c6fc53c574299ecc7f9ee22e" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variant_configs" ADD CONSTRAINT "FK_4c5d421775cd5ec71a0991c6005" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variant_configs" ADD CONSTRAINT "FK_db281faece8d98fdae77d01a0ce" FOREIGN KEY ("inventory_detail_id") REFERENCES "inventory_details"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_834b52ac77bc55fc5d0eb014ae2" FOREIGN KEY ("inventory_id") REFERENCES "inventories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_c1af9b47239151e255f62e03247" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_4b9f1600a4f721ac017eefb03ee" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_edd714311619a5ad09525045838" FOREIGN KEY ("cartId") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_72679d98b31c737937b8932ebe6" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_69828a178f152f157dcf2f70a89" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_cdb99c05982d5191ac8465ac010" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_deliveries" ADD CONSTRAINT "FK_94cf945317a07ebc61a934fd504" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_1ca7d5228cf9dc589b60243933c" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_078644fd27c969e266344e972d6" FOREIGN KEY ("changed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_2f916ebd21611fb8a6911ade4d6" FOREIGN KEY ("guest_customer_id") REFERENCES "guest_customers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_0dddcc76db9733e86e566e5e632" FOREIGN KEY ("deliveryId") REFERENCES "order_deliveries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_5c3bec1682252c36fa161587738" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_4a137ccc372acb73821c4dd3991" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_d4af19c30333db94b91e7f96722" FOREIGN KEY ("inventory_detail_id") REFERENCES "inventory_details"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_d4af19c30333db94b91e7f96722"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_4a137ccc372acb73821c4dd3991"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_5c3bec1682252c36fa161587738"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_0dddcc76db9733e86e566e5e632"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_2f916ebd21611fb8a6911ade4d6"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_078644fd27c969e266344e972d6"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_1ca7d5228cf9dc589b60243933c"`);
        await queryRunner.query(`ALTER TABLE "order_deliveries" DROP CONSTRAINT "FK_94cf945317a07ebc61a934fd504"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_cdb99c05982d5191ac8465ac010"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_69828a178f152f157dcf2f70a89"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_72679d98b31c737937b8932ebe6"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_edd714311619a5ad09525045838"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_4b9f1600a4f721ac017eefb03ee"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_c1af9b47239151e255f62e03247"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_834b52ac77bc55fc5d0eb014ae2"`);
        await queryRunner.query(`ALTER TABLE "product_variant_configs" DROP CONSTRAINT "FK_db281faece8d98fdae77d01a0ce"`);
        await queryRunner.query(`ALTER TABLE "product_variant_configs" DROP CONSTRAINT "FK_4c5d421775cd5ec71a0991c6005"`);
        await queryRunner.query(`ALTER TABLE "product_tags" DROP CONSTRAINT "FK_5b0c6fc53c574299ecc7f9ee22e"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "inventories" DROP CONSTRAINT "FK_92fc0c77bab4a656b9619322c62"`);
        await queryRunner.query(`ALTER TABLE "inventories" DROP CONSTRAINT "FK_5f8ef4645f837ca835e90d78c5c"`);
        await queryRunner.query(`ALTER TABLE "inventories" DROP CONSTRAINT "FK_85e09f62b3421df796c3eb3f687"`);
        await queryRunner.query(`ALTER TABLE "inventories" DROP CONSTRAINT "FK_3bed26289926c1ad4a08d4c7285"`);
        await queryRunner.query(`ALTER TABLE "inventory_details" DROP CONSTRAINT "FK_f11f9f675827128cf1d7418bc53"`);
        await queryRunner.query(`ALTER TABLE "inventory_details" DROP CONSTRAINT "FK_b6dfdb4875a0860ba9f89bb2e93"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP CONSTRAINT "FK_e6b43e8b9b8a6ecf77f34bf86a4"`);
        await queryRunner.query(`ALTER TABLE "purchase_status_history" DROP CONSTRAINT "FK_5b3437860a4a85266ee81df095e"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchase_items" DROP CONSTRAINT "FK_6c99b78100e3d0b47a64aae7ca0"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP CONSTRAINT "FK_839283a834244be65640b1e65e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43f20df28ee6de4d544a9b3972"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e37cfe037f4a370e4494b0eae3"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "status" character varying(50) NOT NULL DEFAULT 'PENDIENTE'`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" ADD "type" character varying(50) NOT NULL DEFAULT 'PENDIENTE'`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "inventory_id"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "invoice_url"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "total_quantity"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "total_amount"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "product_name"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "gender"`);
        await queryRunner.query(`DROP TYPE "public"."product_gender_enum"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "brand"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "purchase_date"`);
        await queryRunner.query(`ALTER TABLE "supplier_purchases" DROP COLUMN "reference"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "inventory_movements"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_movement_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_movements_type_enum"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_delivery_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_status_history"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_history_status_after_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_history_status_before_enum"`);
        await queryRunner.query(`DROP TABLE "guest_customers"`);
        await queryRunner.query(`DROP TABLE "order_deliveries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8387ed27b3d4ca53ec3fc7b029"`);
        await queryRunner.query(`DROP TABLE "branches"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b85ba602ae65eb5813f09e3cec"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "carts"`);
        await queryRunner.query(`DROP TABLE "cart_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1846199852a695713b1f8f5e9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_166502bbaa3dfc7a5a7ac62c64"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_995d8194c43edfc98838cabc5a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0166bf08eec9642fecc5da3c9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89e3b22b462d6443591a1ced4b"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP TABLE "product_variant_configs"`);
        await queryRunner.query(`DROP TABLE "product_tags"`);
        await queryRunner.query(`DROP TABLE "product_images"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fec544b61606dfdf6e6a3fbac8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85e09f62b3421df796c3eb3f68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bed26289926c1ad4a08d4c728"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_efd425ab4b2785296c01ac6780"`);
        await queryRunner.query(`DROP TABLE "inventories"`);
        await queryRunner.query(`DROP TYPE "public"."inventories_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_634d300a22785103ea37759377"`);
        await queryRunner.query(`DROP TABLE "inventory_details"`);
        await queryRunner.query(`DROP TABLE "purchase_status_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bb0dbf021a8e44bf92569723b"`);
        await queryRunner.query(`DROP TABLE "supplier_purchase_items"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TABLE "supplier_purchases"`);
    }

}
